### ISSUE TITLE
mod列表不完整

### ISSUE THREAD

**Issue by al-wei** [Trcmoe/LoadedModsExporter-Python#5]
测试1：396mod，只读取170+mod
测试2：273mod，只读取80mod

即使尝试多次也只能获取部分，然后就获取不了更多数据了。

**Comment by Trcmoe** [comment]
希望可以提供一下原始的模组列表和输出结果。

**Comment by al-wei** [comment]
> 希望可以提供一下原始的模组列表和输出结果。

1.12.2，不提供1.19.2了，我没有建立1.19打包基础
[lme_export.json](https://github.com/user-attachments/files/17088145/lme_export.json)
curseforge格式如果只要列表打开modlist.html
[modlist.html.zip](https://github.com/user-attachments/files/17088153/modlist.html.zip)

如果需要下载mod

https://github.com/al-wei/al-wei.github.io/blob/main/modpack.zip

**Comment by al-wei** [comment]
需要的话
测试整合包都是这里的
https://www.curseforge.com/members/fanren_/projects

**Comment by al-wei** [comment]
这是我最新测试的内容，382个mod
`Python 3.11.9 (tags/v3.11.9:de54cf5, Apr  2 2024, 10:12:12) [MSC v.1938 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license()" for more information.

= RESTART: C:\Users\86150\Downloads\LME_Final.py
请输入文件夹路径：E:\Minecraft\CFMP\Instances\ALNL\mods
格式化 JSON 数据时出错: Unexpected UTF-8 BOM (decode using utf-8-sig): line 1 column 1 (char 0)
格式化 JSON 数据时出错: Expecting value: line 1 column 334 (char 333)
Traceback (most recent call last):
  File "C:\Users\86150\Downloads\LME_Final.py", line 219, in <module>
    PathHandler(folder_path)
  File "C:\Users\86150\Downloads\LME_Final.py", line 32, in PathHandler
    JarFileHandler(full_path)
  File "C:\Users\86150\Downloads\LME_Final.py", line 66, in JarFileHandler
    LForgeModHandler(folder_path)
  File "C:\Users\86150\Downloads\LME_Final.py", line 119, in LForgeModHandler
    raw_data = info_file.read().decode('utf-8')
UnicodeDecodeError: 'utf-8' codec can't decode bytes in position 401-402: invalid continuation byte
`

**Comment by al-wei** [comment]
这还有个神奇情况，如果读取成功不断开，即可以看见首和尾mod，那么证明没有读取一半，而是完整读取，但是数量不对，100个mod可能少读取接近10个，通过vsc软件什么的搜索modid什么的就可以看出来。

**Comment by Trcmoe** [comment]
这个主要是因为脚本是去固定的地方找到模组信息再汇总输出的，感觉1.12.2时期的Forge模组写的都不是很标准啊…

**Comment by al-wei** [comment]
> 这个主要是因为脚本是去固定的地方找到模组信息再汇总输出的，感觉1.12.2时期的Forge模组写的都不是很标准啊…

那这个少读取几十个无所谓了，比起大局观好得多。
主要是不管 1.12.2 还是 1.19.2，几百个mod只读取一半，就不读取了这个问题，比较值得考虑。

**Comment by al-wei** [comment]
甚至一半都没有，可能只是总量的几分之一。
